//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScpPad2vJoy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScpPad2vJoy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSS,Face Buttons,Button
        ///CIRCLE,,Button
        ///SQUARE,,Button
        ///TRIANGLE,,Button
        ///L1,L1 and R1 Buttons,Button
        ///R1,,Button
        ///L2,&quot;L2 and R2, These can be assigned to either an Axis or a Button&quot;,Button or Axis
        ///R2,,Button or Axis
        ///SELECT_SHARE,&quot;Select on a DS3, Share on a DS4.&quot;,Button
        ///START_OPTIONS,&quot;Start on a DS3, Options on a DS4&quot;,Button
        ///L3,Left stict click,Button
        ///R3,Right stick click,Button
        ///PS,Playstation home button,Button
        ///UP,Dpad buttons,Button
        ///DOWN,,Button
        ///LEFT,,Button
        ///RIGHT,,Button
        ///LX,Left stick Axis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DSButtons {
            get {
                return ResourceManager.GetString("DSButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Scp_All {
            get {
                object obj = ResourceManager.GetObject("Scp_All", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1,vJoy controllers can have upto 128 buttons (from B1 to B128). Any Button can be assigned to them.,Button
        ///B5,,Button
        ///B12,,Button
        ///PU,Dpad Up,Button
        ///PD,Dpad Down,Button
        ///PL,Dpad Left,Button
        ///PR,Dpad Right,Button
        ///AX,X-Axis. Left Stick (Left and Right),Axis
        ///AY,Y-Axis. Left Stick (Up and Down),Axis
        ///AZ,Z-Axis. Sometimes used for right stick,Axis
        ///ARX,X Rotation. Sometimes used for right stick,Axis
        ///ARY,Y Rotation. Sometimes used for right stick,Axis
        ///ARZ,Z Rotation,Axis
        ///ASL0,Slider,Axis
        ///ASL1,&quot;Second Sl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vJoyButtons {
            get {
                return ResourceManager.GetString("vJoyButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Mapping taken from https://dvcs.w3.org/hg/gamepad/raw-file/default/gamepad.html#remapping
        ///
        ///B1=CROSS
        ///B2=CIRCLE
        ///B3=SQUARE
        ///B4=TRIANGLE
        ///B5=L1
        ///B6=R1
        ///B7=L2
        ///B8=R2
        ///B9=SELECT_SHARE
        ///B10=START_OPTIONS
        ///B11=L3
        ///B12=R3
        ///B13=PS
        ///PU=UP
        ///PD=DOWN
        ///PL=LEFT
        ///PR=RIGHT
        ///AX=LX
        ///AY=LY
        ///AZ=RX
        ///ARX=RY
        ///ARY=
        ///ARZ=
        ///ASL0=
        ///ASL1=.
        /// </summary>
        public static string W3C {
            get {
                return ResourceManager.GetString("W3C", resourceCulture);
            }
        }
    }
}
